// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUnKlL8GSsczd5hZNUMda8VBmx2UWekNQ',
    appId: '1:256814003117:web:b31eeb3d1b21b2a3522724',
    messagingSenderId: '256814003117',
    projectId: 'projecttutorial-5557e',
    authDomain: 'projecttutorial-5557e.firebaseapp.com',
    storageBucket: 'projecttutorial-5557e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIzPJjOM73C0lWzyeRSc19zwxTmMMV45Q',
    appId: '1:256814003117:android:1f415666c248aa2c522724',
    messagingSenderId: '256814003117',
    projectId: 'projecttutorial-5557e',
    storageBucket: 'projecttutorial-5557e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQVwZqK0QWexnZdR8GS2UZwBnjQtC2ynM',
    appId: '1:256814003117:ios:2e976a4f9559ca15522724',
    messagingSenderId: '256814003117',
    projectId: 'projecttutorial-5557e',
    storageBucket: 'projecttutorial-5557e.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQVwZqK0QWexnZdR8GS2UZwBnjQtC2ynM',
    appId: '1:256814003117:ios:bf5f5e169ff2d4a6522724',
    messagingSenderId: '256814003117',
    projectId: 'projecttutorial-5557e',
    storageBucket: 'projecttutorial-5557e.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
